//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.142.0.
namespace Spec.DMN {
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections;
    using System.Xml.Serialization;

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tDMNElement", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("DMNElement", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TArtifact))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TAssociation))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TBusinessContextElement))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TBusinessKnowledgeModel))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TContext))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TDecision))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TDecisionRule))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TDecisionService))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TDecisionTable))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TDefinitions))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TDRGElement))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TElementCollection))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TExpression))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TFunctionDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TInformationItem))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TInputClause))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TInputData))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TInvocation))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TItemDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TKnowledgeSource))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TList))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TLiteralExpression))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TNamedElement))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TOrganizationUnit))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TOutputClause))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TPerformanceIndicator))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TRelation))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TTextAnnotation))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TUnaryTests))]
    public partial class TDMNElement {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("description", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd", DataType = "string")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("extensionElements", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TDMNElementExtensionElements ExtensionElements { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute ("id", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "ID")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute ("label", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "string")]
        public string Label { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<System.Xml.XmlAttribute> _anyAttribute;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAnyAttributeAttribute ()]
        public System.Collections.ObjectModel.Collection<System.Xml.XmlAttribute> AnyAttribute {
            get {
                return this._anyAttribute;
            }
            private set {
                this._anyAttribute = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="TDMNElement" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TDMNElement" /> class.</para>
        /// </summary>
        public TDMNElement () {
            this._anyAttribute = new System.Collections.ObjectModel.Collection<System.Xml.XmlAttribute> ();
        }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("TDMNElementExtensionElements", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    public partial class TDMNElementExtensionElements {

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<System.Xml.XmlElement> _any;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAnyElementAttribute ()]
        public System.Collections.ObjectModel.Collection<System.Xml.XmlElement> Any {
            get {
                return this._any;
            }
            private set {
                this._any = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Any-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool AnySpecified {
            get {
                return (this.Any.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="TDMNElementExtensionElements" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TDMNElementExtensionElements" /> class.</para>
        /// </summary>
        public TDMNElementExtensionElements () {
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.XmlElement> ();
        }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tDMNElementReference", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    public partial class TDMNElementReference {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute ("href", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
        public string Href { get; set; }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tDefinitions", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("definitions", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class TDefinitions : TNamedElement {

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TImport> _import;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("import", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TImport> Import {
            get {
                return this._import;
            }
            private set {
                this._import = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Import-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Import collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool ImportSpecified {
            get {
                return (this.Import.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="TDefinitions" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TDefinitions" /> class.</para>
        /// </summary>
        public TDefinitions () {
            this._import = new System.Collections.ObjectModel.Collection<TImport> ();
            this._itemDefinition = new System.Collections.ObjectModel.Collection<TItemDefinition> ();
            this._drgElement = new System.Collections.ObjectModel.Collection<TDRGElement> ();
            this._artifact = new System.Collections.ObjectModel.Collection<TArtifact> ();
            this._elementCollection = new System.Collections.ObjectModel.Collection<TElementCollection> ();
            this._businessContextElement = new System.Collections.ObjectModel.Collection<TBusinessContextElement> ();
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TItemDefinition> _itemDefinition;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("itemDefinition", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TItemDefinition> ItemDefinition {
            get {
                return this._itemDefinition;
            }
            private set {
                this._itemDefinition = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die ItemDefinition-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the ItemDefinition collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool ItemDefinitionSpecified {
            get {
                return (this.ItemDefinition.Count != 0);
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TDRGElement> _drgElement;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("drgElement", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TDRGElement> DrgElement {
            get {
                return this._drgElement;
            }
            private set {
                this._drgElement = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die DrgElement-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the DrgElement collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool DrgElementSpecified {
            get {
                return (this.DrgElement.Count != 0);
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TArtifact> _artifact;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("artifact", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TArtifact> Artifact {
            get {
                return this._artifact;
            }
            private set {
                this._artifact = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Artifact-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Artifact collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool ArtifactSpecified {
            get {
                return (this.Artifact.Count != 0);
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TElementCollection> _elementCollection;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("elementCollection", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TElementCollection> ElementCollection {
            get {
                return this._elementCollection;
            }
            private set {
                this._elementCollection = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die ElementCollection-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the ElementCollection collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool ElementCollectionSpecified {
            get {
                return (this.ElementCollection.Count != 0);
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TBusinessContextElement> _businessContextElement;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("businessContextElement", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TBusinessContextElement> BusinessContextElement {
            get {
                return this._businessContextElement;
            }
            private set {
                this._businessContextElement = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die BusinessContextElement-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the BusinessContextElement collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool BusinessContextElementSpecified {
            get {
                return (this.BusinessContextElement.Count != 0);
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private string _expressionLanguage = "http://www.omg.org/spec/FEEL/20140401";

        /// <summary>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute ("http://www.omg.org/spec/FEEL/20140401")]
        [System.Xml.Serialization.XmlAttributeAttribute ("expressionLanguage", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
        public string ExpressionLanguage {
            get {
                return this._expressionLanguage;
            }
            set {
                this._expressionLanguage = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private string _typeLanguage = "http://www.omg.org/spec/FEEL/20140401";

        /// <summary>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute ("http://www.omg.org/spec/FEEL/20140401")]
        [System.Xml.Serialization.XmlAttributeAttribute ("typeLanguage", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
        public string TypeLanguage {
            get {
                return this._typeLanguage;
            }
            set {
                this._typeLanguage = value;
            }
        }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute ("namespace", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
        public string Namespace { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute ("exporter", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "string")]
        public string Exporter { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute ("exporterVersion", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "string")]
        public string ExporterVersion { get; set; }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tNamedElement", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("namedElement", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TBusinessContextElement))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TBusinessKnowledgeModel))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TDecision))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TDecisionService))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TDefinitions))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TDRGElement))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TElementCollection))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TInformationItem))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TInputData))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TItemDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TKnowledgeSource))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TOrganizationUnit))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TPerformanceIndicator))]
    public partial class TNamedElement : TDMNElement {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute ("name", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "string")]
        public string Name { get; set; }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tImport", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("import", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TImportedValues))]
    public partial class TImport {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute ("namespace", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
        public string Namespace { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute ("locationURI", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
        public string LocationURI { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute ("importType", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
        public string ImportType { get; set; }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tItemDefinition", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("itemDefinition", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class TItemDefinition : TNamedElement {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("typeRef", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd", DataType = "QName")]
        public System.Xml.XmlQualifiedName TypeRef { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("allowedValues", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TUnaryTests AllowedValues { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TItemDefinition> _itemComponent;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("itemComponent", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TItemDefinition> ItemComponent {
            get {
                return this._itemComponent;
            }
            private set {
                this._itemComponent = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die ItemComponent-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the ItemComponent collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool ItemComponentSpecified {
            get {
                return (this.ItemComponent.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="TItemDefinition" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TItemDefinition" /> class.</para>
        /// </summary>
        public TItemDefinition () {
            this._itemComponent = new System.Collections.ObjectModel.Collection<TItemDefinition> ();
        }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute ("typeLanguage", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
        public string TypeLanguage { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private bool _isCollection = false;

        /// <summary>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute (false)]
        [System.Xml.Serialization.XmlAttributeAttribute ("isCollection", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "boolean")]
        public bool IsCollection {
            get {
                return this._isCollection;
            }
            set {
                this._isCollection = value;
            }
        }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tUnaryTests", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    public partial class TUnaryTests : TDMNElement {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("text", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd", DataType = "string")]
        public string Text { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute ("expressionLanguage", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
        public string ExpressionLanguage { get; set; }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tDRGElement", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("drgElement", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TBusinessKnowledgeModel))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TDecision))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TInputData))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TKnowledgeSource))]
    public partial class TDRGElement : TNamedElement { }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tArtifact", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("artifact", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TAssociation))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TTextAnnotation))]
    public partial class TArtifact : TDMNElement { }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tElementCollection", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("elementCollection", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class TElementCollection : TNamedElement {

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TDMNElementReference> _drgElement;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("drgElement", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TDMNElementReference> DrgElement {
            get {
                return this._drgElement;
            }
            private set {
                this._drgElement = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die DrgElement-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the DrgElement collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool DrgElementSpecified {
            get {
                return (this.DrgElement.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="TElementCollection" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TElementCollection" /> class.</para>
        /// </summary>
        public TElementCollection () {
            this._drgElement = new System.Collections.ObjectModel.Collection<TDMNElementReference> ();
        }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tBusinessContextElement", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("businessContextElement", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TOrganizationUnit))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TPerformanceIndicator))]
    public partial class TBusinessContextElement : TNamedElement {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute ("URI", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
        public string URI { get; set; }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tDecision", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("decision", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class TDecision : TDRGElement {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("question", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd", DataType = "string")]
        public string Question { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("allowedAnswers", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd", DataType = "string")]
        public string AllowedAnswers { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("variable", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TInformationItem Variable { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TInformationRequirement> _informationRequirement;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("informationRequirement", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TInformationRequirement> InformationRequirement {
            get {
                return this._informationRequirement;
            }
            private set {
                this._informationRequirement = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die InformationRequirement-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the InformationRequirement collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool InformationRequirementSpecified {
            get {
                return (this.InformationRequirement.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="TDecision" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TDecision" /> class.</para>
        /// </summary>
        public TDecision () {
            this._informationRequirement = new System.Collections.ObjectModel.Collection<TInformationRequirement> ();
            this._knowledgeRequirement = new System.Collections.ObjectModel.Collection<TKnowledgeRequirement> ();
            this._authorityRequirement = new System.Collections.ObjectModel.Collection<TAuthorityRequirement> ();
            this._supportedObjective = new System.Collections.ObjectModel.Collection<TDMNElementReference> ();
            this._impactedPerformanceIndicator = new System.Collections.ObjectModel.Collection<TDMNElementReference> ();
            this._decisionMaker = new System.Collections.ObjectModel.Collection<TDMNElementReference> ();
            this._decisionOwner = new System.Collections.ObjectModel.Collection<TDMNElementReference> ();
            this._usingProcess = new System.Collections.ObjectModel.Collection<TDMNElementReference> ();
            this._usingTask = new System.Collections.ObjectModel.Collection<TDMNElementReference> ();
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TKnowledgeRequirement> _knowledgeRequirement;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("knowledgeRequirement", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TKnowledgeRequirement> KnowledgeRequirement {
            get {
                return this._knowledgeRequirement;
            }
            private set {
                this._knowledgeRequirement = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die KnowledgeRequirement-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the KnowledgeRequirement collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool KnowledgeRequirementSpecified {
            get {
                return (this.KnowledgeRequirement.Count != 0);
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TAuthorityRequirement> _authorityRequirement;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("authorityRequirement", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TAuthorityRequirement> AuthorityRequirement {
            get {
                return this._authorityRequirement;
            }
            private set {
                this._authorityRequirement = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die AuthorityRequirement-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the AuthorityRequirement collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool AuthorityRequirementSpecified {
            get {
                return (this.AuthorityRequirement.Count != 0);
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TDMNElementReference> _supportedObjective;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("supportedObjective", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TDMNElementReference> SupportedObjective {
            get {
                return this._supportedObjective;
            }
            private set {
                this._supportedObjective = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die SupportedObjective-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the SupportedObjective collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool SupportedObjectiveSpecified {
            get {
                return (this.SupportedObjective.Count != 0);
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TDMNElementReference> _impactedPerformanceIndicator;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("impactedPerformanceIndicator", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TDMNElementReference> ImpactedPerformanceIndicator {
            get {
                return this._impactedPerformanceIndicator;
            }
            private set {
                this._impactedPerformanceIndicator = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die ImpactedPerformanceIndicator-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the ImpactedPerformanceIndicator collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool ImpactedPerformanceIndicatorSpecified {
            get {
                return (this.ImpactedPerformanceIndicator.Count != 0);
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TDMNElementReference> _decisionMaker;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("decisionMaker", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TDMNElementReference> DecisionMaker {
            get {
                return this._decisionMaker;
            }
            private set {
                this._decisionMaker = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die DecisionMaker-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the DecisionMaker collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool DecisionMakerSpecified {
            get {
                return (this.DecisionMaker.Count != 0);
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TDMNElementReference> _decisionOwner;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("decisionOwner", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TDMNElementReference> DecisionOwner {
            get {
                return this._decisionOwner;
            }
            private set {
                this._decisionOwner = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die DecisionOwner-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the DecisionOwner collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool DecisionOwnerSpecified {
            get {
                return (this.DecisionOwner.Count != 0);
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TDMNElementReference> _usingProcess;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("usingProcess", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TDMNElementReference> UsingProcess {
            get {
                return this._usingProcess;
            }
            private set {
                this._usingProcess = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die UsingProcess-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the UsingProcess collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool UsingProcessSpecified {
            get {
                return (this.UsingProcess.Count != 0);
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TDMNElementReference> _usingTask;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("usingTask", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TDMNElementReference> UsingTask {
            get {
                return this._usingTask;
            }
            private set {
                this._usingTask = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die UsingTask-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the UsingTask collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool UsingTaskSpecified {
            get {
                return (this.UsingTask.Count != 0);
            }
        }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("expression", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TExpression Expression { get; set; }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tInformationItem", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("informationItem", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class TInformationItem : TNamedElement {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute ("typeRef", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "QName")]
        public System.Xml.XmlQualifiedName TypeRef { get; set; }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tInformationRequirement", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    public partial class TInformationRequirement {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("requiredDecision", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TDMNElementReference RequiredDecision { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("requiredInput", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TDMNElementReference RequiredInput { get; set; }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tKnowledgeRequirement", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    public partial class TKnowledgeRequirement {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("requiredKnowledge", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TDMNElementReference RequiredKnowledge { get; set; }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tAuthorityRequirement", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    public partial class TAuthorityRequirement {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("requiredDecision", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TDMNElementReference RequiredDecision { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("requiredInput", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TDMNElementReference RequiredInput { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("requiredAuthority", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TDMNElementReference RequiredAuthority { get; set; }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tExpression", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("expression", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TContext))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TDecisionTable))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TFunctionDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TInvocation))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TList))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TLiteralExpression))]
    [System.Xml.Serialization.XmlIncludeAttribute (typeof (TRelation))]
    public partial class TExpression : TDMNElement {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute ("typeRef", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "QName")]
        public System.Xml.XmlQualifiedName TypeRef { get; set; }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tPerformanceIndicator", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("performanceIndicator", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class TPerformanceIndicator : TBusinessContextElement {

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TDMNElementReference> _impactingDecision;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("impactingDecision", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TDMNElementReference> ImpactingDecision {
            get {
                return this._impactingDecision;
            }
            private set {
                this._impactingDecision = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die ImpactingDecision-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the ImpactingDecision collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool ImpactingDecisionSpecified {
            get {
                return (this.ImpactingDecision.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="TPerformanceIndicator" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TPerformanceIndicator" /> class.</para>
        /// </summary>
        public TPerformanceIndicator () {
            this._impactingDecision = new System.Collections.ObjectModel.Collection<TDMNElementReference> ();
        }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tOrganizationUnit", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("organizationUnit", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class TOrganizationUnit : TBusinessContextElement {

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TDMNElementReference> _decisionMade;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("decisionMade", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TDMNElementReference> DecisionMade {
            get {
                return this._decisionMade;
            }
            private set {
                this._decisionMade = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die DecisionMade-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the DecisionMade collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool DecisionMadeSpecified {
            get {
                return (this.DecisionMade.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="TOrganizationUnit" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TOrganizationUnit" /> class.</para>
        /// </summary>
        public TOrganizationUnit () {
            this._decisionMade = new System.Collections.ObjectModel.Collection<TDMNElementReference> ();
            this._decisionOwned = new System.Collections.ObjectModel.Collection<TDMNElementReference> ();
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TDMNElementReference> _decisionOwned;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("decisionOwned", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TDMNElementReference> DecisionOwned {
            get {
                return this._decisionOwned;
            }
            private set {
                this._decisionOwned = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die DecisionOwned-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the DecisionOwned collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool DecisionOwnedSpecified {
            get {
                return (this.DecisionOwned.Count != 0);
            }
        }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tBusinessKnowledgeModel", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("businessKnowledgeModel", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class TBusinessKnowledgeModel : TDRGElement {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("encapsulatedLogic", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TFunctionDefinition EncapsulatedLogic { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("variable", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TInformationItem Variable { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TKnowledgeRequirement> _knowledgeRequirement;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("knowledgeRequirement", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TKnowledgeRequirement> KnowledgeRequirement {
            get {
                return this._knowledgeRequirement;
            }
            private set {
                this._knowledgeRequirement = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die KnowledgeRequirement-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the KnowledgeRequirement collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool KnowledgeRequirementSpecified {
            get {
                return (this.KnowledgeRequirement.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="TBusinessKnowledgeModel" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TBusinessKnowledgeModel" /> class.</para>
        /// </summary>
        public TBusinessKnowledgeModel () {
            this._knowledgeRequirement = new System.Collections.ObjectModel.Collection<TKnowledgeRequirement> ();
            this._authorityRequirement = new System.Collections.ObjectModel.Collection<TAuthorityRequirement> ();
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TAuthorityRequirement> _authorityRequirement;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("authorityRequirement", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TAuthorityRequirement> AuthorityRequirement {
            get {
                return this._authorityRequirement;
            }
            private set {
                this._authorityRequirement = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die AuthorityRequirement-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the AuthorityRequirement collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool AuthorityRequirementSpecified {
            get {
                return (this.AuthorityRequirement.Count != 0);
            }
        }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tFunctionDefinition", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("functionDefinition", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class TFunctionDefinition : TExpression {

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TInformationItem> _formalParameter;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("formalParameter", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TInformationItem> FormalParameter {
            get {
                return this._formalParameter;
            }
            private set {
                this._formalParameter = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die FormalParameter-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the FormalParameter collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool FormalParameterSpecified {
            get {
                return (this.FormalParameter.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="TFunctionDefinition" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TFunctionDefinition" /> class.</para>
        /// </summary>
        public TFunctionDefinition () {
            this._formalParameter = new System.Collections.ObjectModel.Collection<TInformationItem> ();
        }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("expression", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TExpression Expression { get; set; }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tInputData", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("inputData", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class TInputData : TDRGElement {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("variable", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TInformationItem Variable { get; set; }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tKnowledgeSource", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("knowledgeSource", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class TKnowledgeSource : TDRGElement {

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TAuthorityRequirement> _authorityRequirement;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("authorityRequirement", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TAuthorityRequirement> AuthorityRequirement {
            get {
                return this._authorityRequirement;
            }
            private set {
                this._authorityRequirement = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die AuthorityRequirement-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the AuthorityRequirement collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool AuthorityRequirementSpecified {
            get {
                return (this.AuthorityRequirement.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="TKnowledgeSource" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TKnowledgeSource" /> class.</para>
        /// </summary>
        public TKnowledgeSource () {
            this._authorityRequirement = new System.Collections.ObjectModel.Collection<TAuthorityRequirement> ();
        }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("type", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd", DataType = "string")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("owner", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TDMNElementReference Owner { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute ("locationURI", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
        public string LocationURI { get; set; }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tLiteralExpression", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("literalExpression", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class TLiteralExpression : TExpression {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("text", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd", DataType = "string")]
        public string Text { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("importedValues", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TImportedValues ImportedValues { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute ("expressionLanguage", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
        public string ExpressionLanguage { get; set; }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tImportedValues", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    public partial class TImportedValues : TImport {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("importedElement", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd", DataType = "string")]
        public string ImportedElement { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute ("expressionLanguage", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
        public string ExpressionLanguage { get; set; }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tInvocation", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("invocation", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class TInvocation : TExpression {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("expression", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TExpression Expression { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TBinding> _binding;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("binding", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TBinding> Binding {
            get {
                return this._binding;
            }
            private set {
                this._binding = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Binding-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Binding collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool BindingSpecified {
            get {
                return (this.Binding.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="TInvocation" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TInvocation" /> class.</para>
        /// </summary>
        public TInvocation () {
            this._binding = new System.Collections.ObjectModel.Collection<TBinding> ();
        }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tBinding", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    public partial class TBinding {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("parameter", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TInformationItem Parameter { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("expression", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TExpression Expression { get; set; }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tDecisionTable", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("decisionTable", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class TDecisionTable : TExpression {

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TInputClause> _input;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("input", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TInputClause> Input {
            get {
                return this._input;
            }
            private set {
                this._input = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Input-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Input collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool InputSpecified {
            get {
                return (this.Input.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="TDecisionTable" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TDecisionTable" /> class.</para>
        /// </summary>
        public TDecisionTable () {
            this._input = new System.Collections.ObjectModel.Collection<TInputClause> ();
            this._output = new System.Collections.ObjectModel.Collection<TOutputClause> ();
            this._rule = new System.Collections.ObjectModel.Collection<TDecisionRule> ();
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TOutputClause> _output;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("output", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TOutputClause> Output {
            get {
                return this._output;
            }
            private set {
                this._output = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TDecisionRule> _rule;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("rule", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TDecisionRule> Rule {
            get {
                return this._rule;
            }
            private set {
                this._rule = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Rule-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Rule collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool RuleSpecified {
            get {
                return (this.Rule.Count != 0);
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private THitPolicy _hitPolicy = Spec.DMN.THitPolicy.UNIQUE;

        /// <summary>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute (Spec.DMN.THitPolicy.UNIQUE)]
        [System.Xml.Serialization.XmlAttributeAttribute ("hitPolicy", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public THitPolicy HitPolicy {
            get {
                return this._hitPolicy;
            }
            set {
                this._hitPolicy = value;
            }
        }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute ("aggregation", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TBuiltinAggregator Aggregation { get; set; }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Aggregation-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Aggregation property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool AggregationSpecified { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private TDecisionTableOrientation _preferredOrientation = Spec.DMN.TDecisionTableOrientation.Rule_As_Row;

        /// <summary>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute (Spec.DMN.TDecisionTableOrientation.Rule_As_Row)]
        [System.Xml.Serialization.XmlAttributeAttribute ("preferredOrientation", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TDecisionTableOrientation PreferredOrientation {
            get {
                return this._preferredOrientation;
            }
            set {
                this._preferredOrientation = value;
            }
        }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute ("outputLabel", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "string")]
        public string OutputLabel { get; set; }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tInputClause", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    public partial class TInputClause : TDMNElement {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("inputExpression", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TLiteralExpression InputExpression { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("inputValues", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TUnaryTests InputValues { get; set; }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tOutputClause", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    public partial class TOutputClause : TDMNElement {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("outputValues", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TUnaryTests OutputValues { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("defaultOutputEntry", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TLiteralExpression DefaultOutputEntry { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute ("name", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "string")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute ("typeRef", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "QName")]
        public System.Xml.XmlQualifiedName TypeRef { get; set; }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tDecisionRule", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    public partial class TDecisionRule : TDMNElement {

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TUnaryTests> _inputEntry;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("inputEntry", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TUnaryTests> InputEntry {
            get {
                return this._inputEntry;
            }
            private set {
                this._inputEntry = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die InputEntry-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the InputEntry collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool InputEntrySpecified {
            get {
                return (this.InputEntry.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="TDecisionRule" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TDecisionRule" /> class.</para>
        /// </summary>
        public TDecisionRule () {
            this._inputEntry = new System.Collections.ObjectModel.Collection<TUnaryTests> ();
            this._outputEntry = new System.Collections.ObjectModel.Collection<TLiteralExpression> ();
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TLiteralExpression> _outputEntry;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("outputEntry", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TLiteralExpression> OutputEntry {
            get {
                return this._outputEntry;
            }
            private set {
                this._outputEntry = value;
            }
        }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tHitPolicy", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public enum THitPolicy {

        /// <summary>
        /// </summary>
        UNIQUE,

        /// <summary>
        /// </summary>
        FIRST,

        /// <summary>
        /// </summary>
        PRIORITY,

        /// <summary>
        /// </summary>
        ANY,

        /// <summary>
        /// </summary>
        COLLECT,

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute ("RULE ORDER")]
        RULE_ORDER,

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute ("OUTPUT ORDER")]
        OUTPUT_ORDER,
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tBuiltinAggregator", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public enum TBuiltinAggregator {

        /// <summary>
        /// </summary>
        SUM,

        /// <summary>
        /// </summary>
        COUNT,

        /// <summary>
        /// </summary>
        MIN,

        /// <summary>
        /// </summary>
        MAX,
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tDecisionTableOrientation", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public enum TDecisionTableOrientation {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute ("Rule-as-Row")]
        Rule_As_Row,

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute ("Rule-as-Column")]
        Rule_As_Column,

        /// <summary>
        /// </summary>
        CrossTable,
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tTextAnnotation", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("textAnnotation", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class TTextAnnotation : TArtifact {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("text", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd", DataType = "string")]
        public string Text { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private string _textFormat = "text/plain";

        /// <summary>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute ("text/plain")]
        [System.Xml.Serialization.XmlAttributeAttribute ("textFormat", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "string")]
        public string TextFormat {
            get {
                return this._textFormat;
            }
            set {
                this._textFormat = value;
            }
        }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tAssociation", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("association", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class TAssociation : TArtifact {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("sourceRef", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TDMNElementReference SourceRef { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("targetRef", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TDMNElementReference TargetRef { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private TAssociationDirection _associationDirection = Spec.DMN.TAssociationDirection.None;

        /// <summary>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute (Spec.DMN.TAssociationDirection.None)]
        [System.Xml.Serialization.XmlAttributeAttribute ("associationDirection", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TAssociationDirection AssociationDirection {
            get {
                return this._associationDirection;
            }
            set {
                this._associationDirection = value;
            }
        }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tAssociationDirection", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public enum TAssociationDirection {

        /// <summary>
        /// </summary>
        None,

        /// <summary>
        /// </summary>
        One,

        /// <summary>
        /// </summary>
        Both,
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tContext", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("context", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class TContext : TExpression {

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TContextEntry> _contextEntry;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("contextEntry", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TContextEntry> ContextEntry {
            get {
                return this._contextEntry;
            }
            private set {
                this._contextEntry = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die ContextEntry-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the ContextEntry collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool ContextEntrySpecified {
            get {
                return (this.ContextEntry.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="TContext" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TContext" /> class.</para>
        /// </summary>
        public TContext () {
            this._contextEntry = new System.Collections.ObjectModel.Collection<TContextEntry> ();
        }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tContextEntry", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    public partial class TContextEntry {

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("variable", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TInformationItem Variable { get; set; }

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("expression", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public TExpression Expression { get; set; }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tRelation", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("relation", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class TRelation : TExpression {

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TInformationItem> _column;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("column", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TInformationItem> Column {
            get {
                return this._column;
            }
            private set {
                this._column = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Column-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Column collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool ColumnSpecified {
            get {
                return (this.Column.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="TRelation" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TRelation" /> class.</para>
        /// </summary>
        public TRelation () {
            this._column = new System.Collections.ObjectModel.Collection<TInformationItem> ();
            this._row = new System.Collections.ObjectModel.Collection<TList> ();
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TList> _row;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("row", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TList> Row {
            get {
                return this._row;
            }
            private set {
                this._row = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Row-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Row collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool RowSpecified {
            get {
                return (this.Row.Count != 0);
            }
        }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tList", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("list", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class TList : TExpression {

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TExpression> _expression;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("expression", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TExpression> Expression {
            get {
                return this._expression;
            }
            private set {
                this._expression = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Expression-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Expression collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool ExpressionSpecified {
            get {
                return (this.Expression.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="TList" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TList" /> class.</para>
        /// </summary>
        public TList () {
            this._expression = new System.Collections.ObjectModel.Collection<TExpression> ();
        }
    }

    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("XmlSchemaClassGenerator", "2.0.142.0")]
    [System.SerializableAttribute ()]
    [System.Xml.Serialization.XmlTypeAttribute ("tDecisionService", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlRootAttribute ("decisionService", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
    public partial class TDecisionService : TNamedElement {

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TDMNElementReference> _outputDecision;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("outputDecision", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TDMNElementReference> OutputDecision {
            get {
                return this._outputDecision;
            }
            private set {
                this._outputDecision = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="TDecisionService" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TDecisionService" /> class.</para>
        /// </summary>
        public TDecisionService () {
            this._outputDecision = new System.Collections.ObjectModel.Collection<TDMNElementReference> ();
            this._encapsulatedDecision = new System.Collections.ObjectModel.Collection<TDMNElementReference> ();
            this._inputDecision = new System.Collections.ObjectModel.Collection<TDMNElementReference> ();
            this._inputData = new System.Collections.ObjectModel.Collection<TDMNElementReference> ();
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TDMNElementReference> _encapsulatedDecision;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("encapsulatedDecision", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TDMNElementReference> EncapsulatedDecision {
            get {
                return this._encapsulatedDecision;
            }
            private set {
                this._encapsulatedDecision = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die EncapsulatedDecision-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the EncapsulatedDecision collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool EncapsulatedDecisionSpecified {
            get {
                return (this.EncapsulatedDecision.Count != 0);
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TDMNElementReference> _inputDecision;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("inputDecision", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TDMNElementReference> InputDecision {
            get {
                return this._inputDecision;
            }
            private set {
                this._inputDecision = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die InputDecision-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the InputDecision collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool InputDecisionSpecified {
            get {
                return (this.InputDecision.Count != 0);
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        private System.Collections.ObjectModel.Collection<TDMNElementReference> _inputData;

        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute ("inputData", Namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd")]
        public System.Collections.ObjectModel.Collection<TDMNElementReference> InputData {
            get {
                return this._inputData;
            }
            private set {
                this._inputData = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die InputData-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the InputData collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute ()]
        public bool InputDataSpecified {
            get {
                return (this.InputData.Count != 0);
            }
        }
    }
}